services:

  postgres_db:
    container_name: postgres_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DB=test
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork2

networks:
  mynetwork2:
    driver: bridge